

export const getRandomName=() => {
    var a = [
      "John",
      "Smith",
      "Emily",
      "Johnson",
      "Michael",
      "Williams",
      "Emma",
      "Brown",
      "Christopher",
      "Jones",
      "Olivia",
      "Davis",
      "William",
      "Miller",
      "Ava",
      "Wilson",
      "James",
      "Moore",
      "Sophia",
      "Taylor",
      "David",
      "Anderson",
      "Isabella",
      "Thomas",
      "Joseph",
      "Jackson",
      "Charlotte",
      "White",
      "Daniel",
      "Harris",
      "Amelia",
      "Martin",
      "Matthew",
      "Thompson",
      "Ella",
      "Garcia",
      "Alexander",
      "Martinez",
      "Grace",
      "Robinson",
      "Noah",
      "Hernandez",
      "Madison",
      "Young",
      "Ethan",
      "Lee",
      "Chloe",
      "Lewis",
      "Logan",
      "Clark",
      "Natalie",
      "Hall",
      "Benjamin",
      "King",
      "Zoe",
      "Hill",
      "Lucas",
      "Nelson",
      "Lily",
      "Adams",
      "Gabriel",
      "Turner",
      "Hailey",
      "Carter",
      "Samuel",
      "Wright",
      "Avery",
      "Phillips",
      "Ryan",
      "Murphy",
      "Aria",
      "Kelly",
      "Jackson",
      "Rivera",
      "Addison",
      "Parker",
      "Andrew",
      "Cooper",
      "Samantha",
      "Edwards",
      "Anthony",
      "Sanchez",
      "Victoria",
      "Evans",
      "Christopher",
      "Ward",
      "Kaylee",
      "Torres",
      "Isaac",
      "Morris",
      "Bella",
      "Collins",
      "Lincoln",
      "Brooks",
      "Hannah",
      "Richardson",
      "Joshua",
      "Reed",
      "Leah",
      "Wood",
      "Christian",
      "Ross",
      "Katherine",
      "Howard",
      "Wyatt",
      "Ortiz",
      "Audrey",
      "Sanchez",
      "Jonathan",
      "Price",
      "Allison",
      "Rivera",
      "Caleb",
      "Barnes",
      "Lauren",
      "Watson",
      "Owen",
      "Sanders",
      "Evelyn",
      "Bennett",
      "Julian",
      "Coleman",
      "Sofia",
      "Ross",
      "Levi",
      "Jenkins",
      "Brooklyn",
      "Perry",
      "Isaiah",
      "Long",
      "Grace",
      "Kim",
      "Henry",
      "James",
      "Mia",
      "Bailey",
      "Nathan",
      "Foster",
      "Claire",
      "Nguyen",
      "David",
      "Ross",
      "Aaliyah",
      "Gonzalez",
      "Eli",
      "Myers",
      "Ellie",
      "Cook",
      "Samuel",
      "Griffin",
      "Skylar",
      "Russell",
      "Dylan",
      "Diaz",
      "Ruby",
      "Patel",
      "Isaiah",
      "Perry",
      "Madeline",
      "King",
      "Leo",
      "Henderson",
      "Alyssa",
      "Ramirez",
      "Hudson",
      "Ward",
      "Penelope",
      "Gomez",
      "Jeremiah",
      "Murphy",
      "Harper",
      "Hayes",
      "Landon",
      "Price",
      "Nora",
      "Edwards",
      "Nicholas",
      "Long",
      "Maya",
      "Rogers",
      "Evan",
      "Simmons",
      "Maria",
      "Turner",
      "Colton",
      "Cooper",
      "Madelyn",
      "Bell",
      "Josiah",
      "Coleman",
      "Stella",
      "Coleman",
      "Aaron",
      "Morgan",
      "Faith",
      "Johnson",
      "Charles",
      "White",
      "Layla",
      "Torres",
    ];
    var rA = Math.floor(Math.random()*a.length);
    return a[rA];
}


export const generateMessage=(length) =>{
    const commentsList = [
      "Great job on this project!",
      "I love the design!",
      "This is very helpful. Thank you!",
      "Could you provide more details about this?",
      "I'm not sure I understand what you mean.",
      "This is exactly what I was looking for.",
      "I think there might be a mistake here.",
      "Can we discuss this further in the meeting?",
      "I appreciate your hard work.",
      "Wow, this is impressive!",
      "I have a suggestion for improvement.",
      "Please clarify this point.",
      "I'm excited to see the final product!",
      "I'm having trouble with this feature.",
      "Is there a deadline for this task?",
      "Thank you for your prompt response.",
      "This looks perfect!",
      "I'm not sure if this is the right approach.",
      "Could you provide examples to illustrate?",
      "I'm impressed by your attention to detail.",
      "I think we should reconsider this decision.",
      "Let's schedule a follow-up meeting to discuss.",
      "Great work, team!",
      "I'm looking forward to working with you on this.",
      "I'm experiencing some issues with the code.",
      "This is going to be a game-changer!",
      "Let me know if you need any assistance.",
      "I'm confident we can overcome this challenge.",
      "This is a valuable contribution.",
      "I'm not sure if I agree with this proposal.",
      "Thank you for your dedication and effort.",
      "I have some ideas for improvement.",
      "Let's brainstorm some solutions together.",
      "I'm impressed by the progress we've made.",
      "Could you provide more context for this?",
      "I'm excited to see how this project evolves.",
      "I'm concerned about potential risks.",
      "This exceeded my expectations!",
      "I have some concerns about the timeline.",
      "Let's make sure we're all on the same page.",
      "I appreciate your patience and cooperation.",
      "This is a significant milestone.",
      "I'm confident we're headed in the right direction.",
      "I'm not sure if this is feasible within our budget.",
      "Thank you for your collaboration.",
      "I think we need to revisit our strategy.",
      "I'm looking forward to your feedback.",
      "This is a top priority.",
      "I'm impressed by the quality of work.",
      "Let's keep up the momentum!",
      "I have some suggestions for optimization.",
      "This is a critical issue that needs to be addressed.",
      "I'm excited to be part of this team!",
      "I'm not sure if this aligns with our goals.",
      "Can you provide some more information about this?",
      "I'm confident we can find a solution.",
      "This is a major breakthrough!",
      "Let's document our progress for future reference.",
      "I'm having difficulty understanding the requirements.",
      "Thank you for your input.",
      "I think we're making great progress.",
      "I'm concerned about potential obstacles.",
      "This is a fantastic opportunity!",
      "I'm impressed by the level of collaboration.",
      "I'm not sure if this is the best approach.",
      "Let's keep communication channels open.",
      "I'm confident we can overcome any challenges.",
      "This is a significant achievement.",
      "I have some reservations about this idea.",
      "Thank you for your commitment to excellence.",
      "I'm looking forward to seeing this in action.",
      "I'm unsure about the implications of this decision.",
      "Can you provide some more context for this?",
      "I'm excited to see how this unfolds.",
      "I have some questions about the implementation.",
      "This demonstrates our ability to innovate.",
      "I'm not sure if this aligns with our values.",
      "Let's explore alternative options.",
      "I'm confident we can find a resolution.",
      "This showcases our team's strengths.",
      "I'm curious to hear everyone's thoughts.",
      "Thank you for your dedication to this project.",
      "I'm excited about the potential of this idea.",
      "I'm not sure if we've considered all the implications.",
      "Let's ensure everyone is on board with this.",
      "I'm impressed by the level of creativity.",
      "I'm concerned about potential roadblocks.",
      "This is a testament to our hard work.",
      "I have some ideas for how we can improve.",
      "Let's work together to find a solution.",
      "I'm excited to see where this leads.",
      "I'm not sure if this is the most efficient approach.",
      "Can you provide some insights into this?",
      "I'm confident we can achieve our goals.",
      "This highlights the importance of teamwork.",
      "I'm intrigued by this concept.",
      "I'm not sure if we're considering all the options.",
      "Let's keep pushing forward!",
      "I have some suggestions for how we can proceed.",
      "Thank you for your ongoing support.",
      "I'm excited to see the impact of this project.",
      "I'm unsure about the implications of this decision.",
      "Can you provide some clarification on this?",
      "I'm confident we're moving in the right direction.",
      "This shows what we're capable of achieving.",
      "I'm impressed by the level of dedication.",
      "I'm not sure if this is the best use of resources.",
      "Let's explore different possibilities.",
      "I have some concerns that I'd like to address.",
      "Thank you for your contributions to this project.",
      "I'm excited to see the results of our efforts.",
      "I'm uncertain about the next steps.",
      "Can you provide some guidance on this?",
      "I'm confident we can overcome any obstacles.",
      "This demonstrates our ability to adapt.",
      "I'm impressed by the level of teamwork.",
      "I'm not sure if we've considered all the factors.",
      "Let's brainstorm some solutions together.",
      "I have some ideas for how we can proceed.",
      "Thank you for your collaboration on this.",
      "I'm excited to see how this unfolds.",
      "I'm not sure if this approach is feasible.",
      "Can you provide some additional information?",
      "I'm confident we can find a way forward.",
      "This showcases our team's creativity.",
      "I'm intrigued by this concept.",
      "I'm not sure if we're considering all the possibilities.",
      "Let's keep pushing the boundaries!",
      "I have some suggestions for improvement.",
      "Thank you for your dedication and hard work.",
      "I'm excited to see the results of our efforts.",
      "I'm unsure about the implications of this decision.",
      "Can you provide some clarification on this?",
      "I'm confident we're on the right track.",
      "This demonstrates our ability to innovate.",
      "I'm impressed by the level of collaboration.",
      "I'm not sure if this is the best approach.",
      "Let's explore alternative options.",
      "I have some reservations about this idea.",
      "Thank you for your commitment to excellence.",
  ];
  var rA = Math.floor(Math.random() * commentsList.length);
    return commentsList[rA];
}